# Generated by Django 6.1 on 2026-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Events', 'Events'), ('Policy', 'Policy'), ('Urgent', 'Urgent'), ('General', 'General')], default='Academic', max_length=50)),
                ('audience', models.CharField(choices=[('Public', 'Public'), ('All Students', 'All Students'), ('Parents', 'Parents'), ('Teachers', 'Teachers'), ('Admin', 'Administrative Staff')], default='Public', max_length=50)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Urgent', 'Urgent Announcement'), ('Draft', 'Draft'), ('Archived', 'Archived')], db_index=True, default='Published', max_length=30)),
                ('is_pinned', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
