"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ur";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
  isUrdu: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations Dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar / Common
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.courses": "Courses",
    "nav.admission": "Admission",
    "nav.teachers": "Teachers",
    "nav.notices": "Notices",
    "nav.contact": "Contact",
    "nav.gallery": "Gallery",
    "nav.donation": "Donation",
    "nav.login": "Login",
    "nav.madrasa_name": "Madrasa Al-Umaima",
    "nav.tagline": "Quran & Knowledge",

    // Dashboard Sidebar
    "side.dashboard": "Dashboard",
    "side.profile": "My Profile",
    "side.attendance": "Attendance",
    "side.fees": "Fee Status",
    "side.results": "Results",
    "side.notice": "Notice Board",
    "side.timetable": "Timetable",
    "side.homework": "Homework",
    "side.id_card": "ID Card",
    "side.report_card": "Report Card",
    "side.settings": "Settings",
    "side.logout": "Logout",
    "side.portal": "STUDENT PORTAL",

    // Common UI
    "btn.apply": "Apply now",
    "btn.donate": "Donate Now",
    "btn.learn_more": "Learn More",
    "btn.view_all": "View All",
    "btn.contact_now": "Contact Now",
    "btn.submit": "Submit Message",
    "btn.save": "Save Changes",

    // Home Page
    "hero.title_p1": "A Place for",
    "hero.title_quran": "Quran",
    "hero.title_p2": "Knowledge & Character",
    "hero.subtitle": "Empowering the next generation of Muslim leaders with classical Islamic education.",
    "hero.join_msg": "Join 500+ students on their spiritual journey",
    "hero.join_sub": "Educational sanctuary for the seekers of light.",
    "hero.admissions": "Admissions Open 2026-27",

    // Contact / Forms
    "form.full_name": "Full Name",
    "form.phone": "Phone Number",
    "form.email": "Email Address",
    "form.subject": "Subject",
    "form.message": "Your Detailed Message",
    "form.send": "Deliver Consultation Message",
    "form.location_label": "Our Location",
    "form.call_label": "Direct Call",
    "form.email_label": "Official Email",

    // Profile / ID Card
    "profile.student_id": "Student ID",
    "profile.class": "Class",
    "profile.reg_date": "Reg. Date",
    "profile.roll": "Roll No",
    "id.identity": "Identity Card",

    // Attendance / Fees / Stats
    "stat.present": "Present",
    "stat.absent": "Absent",
    "stat.late": "Late",
    "stat.paid": "Paid",
    "stat.pending": "Pending",
    "stat.overdue": "Overdue",

    // Dashboard / Portal Extra
    "portal.welcome": "Salaam",
    "portal.roll": "Roll No",
    "portal.dashboard": "Student Dashboard",
    "portal.quick_actions": "Quick Actions",
    "portal.id_card_btn": "ID Card View",
    "portal.report_card_btn": "Report Card",
    "portal.stats.attendance": "Attendance %",
    "portal.stats.fees": "Pending Fees",
    "portal.stats.course": "Current Course",
    "portal.alert.title": "Student Alerts",
    "portal.alert.recent": "Important Notices",
    "portal.alert.view": "View Performance Details",
    "portal.recognition": "Recognition",
    "portal.student_month": "Student of the Month Candidate",

    // Admission Page Extra
    "admission.hero.title": "Apply For",
    "admission.hero.accent": "Admission",
    "admission.hero.sub": "Join the legacy of Quranic and Scientific excellence.",
    "admission.process": "Selection Process",
    "admission.docs": "Required Documents",
    "admission.form.title": "Online Admission Form",
    "admission.form.sub": "Please provide authentic data only",
    "admission.form.student_name": "Full Name of Student",
    "admission.form.parent_name": "Father/Guardian Name",
    "admission.form.dob": "Date of Birth",
    "admission.form.btn": "Submit Admission Inquiry",

    // Home Page - About Section
    "about.legacy": "Our Legacy",
    "about.title": "Nurturing Souls Since 1998",
    "about.desc1": "Madrasa Al-Umaima was founded with a singular vision: to create a sanctuary where the heart meets knowledge. We believe that true education transcends books — it is about the transformation of character.",
    "about.desc2": "Our curriculum follows the classical \"Dars-e-Nizami\" method while integrating modern communication skills and scientific literacy.",
    "about.vision_label": "Vision",
    "about.vision_text": "Empowering Ummah through authentic knowledge",
    "about.values_label": "Values",
    "about.values_text": "Ikhlas, Excellence, Integrity, Service",
    "about.learn_more": "Learn More About Our Journey",
    "about.masjid_learning": "Masjid-Based Learning",
    "about.hifz_program": "Classical Hifz Program",
    "about.student_centered": "Student Centered",
    "about.global_standards": "Global Standards",

    // Why Choose Us Section
    "why.title": "Why Choose Al-Umaima?",
    "why.subtitle": "\"Seeking knowledge is a religious duty for every Muslim.\" - Hadith",
    "why.feat1_title": "Qualified Teachers",
    "why.feat1_desc": "Learn from recognized Ulema and Huffaz with years of experience and deep spiritual insight.",
    "why.feat2_title": "Safe Learning Environment",
    "why.feat2_desc": "Specially designed spaces that foster focus, discipline, and spiritual growth for all ages.",
    "why.feat3_title": "Character Building",
    "why.feat3_desc": "We focus on Akhlaq as much as Academia, preparing students for life, not just exams.",
    "why.feat4_title": "Quran & Islamic Education",
    "why.feat4_desc": "Comprehensive modules covering Tajweed, Fiqh, Sera, and Islamic History.",
    "why.feat5_title": "Affordable Education",
    "why.feat5_desc": "Multiple scholarship programs and flexible fee structures to ensure knowledge is accessible.",
    "why.feat6_title": "Community Support",
    "why.feat6_desc": "Strong bonds with parents and local community through regular meetings and workshops.",

    // Course Preview
    "course.label": "Our Core Programs",
    "course.title": "Educational Excellence",
    "course.view_all": "View All Courses",
    "course.enroll_now": "Enroll Now",
    "course.c1_title": "Nazra Quran",
    "course.c1_desc": "Basic reading with proper Tajweed rules for beginners.",
    "course.c2_title": "Hifz-ul-Quran",
    "course.c2_desc": "Memorization of Quran with beautiful Tajweed recitation.",
    "course.c3_title": "Urdu & Arabic",
    "course.c3_desc": "Master the language of the Quran and regional literature.",
    "course.c4_title": "Islamic Studies",
    "course.c4_desc": "Comprehensive course on Fiqh, Seerah, and Hadith.",
    "course.time_1y": "1 Year",
    "course.time_34y": "3-4 Years",
    "course.time_2y": "2 Years",
    "course.fee_monthly": "Monthly",
    "course.fee_semester": "Semester",
    "course.fee_free": "Free",

    // Founder Section
    "founder.badge": "A Message From Leadership",
    "founder.title": "Wisdom Beyond Words",
    "founder.msg": "\"At Madrasa Al-Umaima, we are not just teaching students how to read; we are teaching them how to live. Our mission is to plant the seeds of knowledge in hearts so they may grow into trees of wisdom that shelter the entire Ummah.\"",
    "founder.name": "Maulana Abdul Umaima",
    "founder.role": "Master of Islamic Jurisprudence (Alim)",
    "founder.designation": "Founder & Principal",
    "founder.link": "Full Profile of Our Educators",

    // Stats Section
    "stats.students": "Students",
    "stats.alumni": "Alumni",
    "stats.teachers": "Teachers",
    "stats.courses": "Courses",

    // Notice Board Section
    "notice.title": "Notice Board",
    "notice.link": "All Announcements",
    "notice.read_more": "Read Details",
    "notice.type_adm": "Admission",
    "notice.type_res": "Result",
    "notice.type_hol": "Holiday",
    "notice.n1_title": "Admission Open 2026",
    "notice.n1_date": "April 15, 2026",
    "notice.n1_desc": "Enrollments for the new academic session are now open for all programs.",
    "notice.n2_title": "Annual Exam Results",
    "notice.n2_date": "May 20, 2026",
    "notice.n2_desc": "Results for the 2025-26 session are now available on the student dashboard.",
    "notice.n3_title": "Ramadan Holidays",
    "notice.n3_date": "Jan 10, 2026",
    "notice.n3_desc": "The Madrasa will remain closed from 20th Ramadan until 5th Shawwal.",

    // Donation Section
    "donation.title": "Support Islamic Education",
    "donation.desc": "Donate your Zakat, Sadaqah, and Lillah to help us provide quality education to deserving students. Every contribution illuminates a heart with knowledge.",
    "donation.btn": "Donate Now",
    "donation.quick_pay": "Quick Payment",
    "donation.scan_qr": "Scan QR to Support",
    "donation.bank": "Bank Account",
    "donation.upi": "UPI ID",
    "donation.phonepay": "PhonePay",

    // Testimonials Section
    "test.label": "Voices of our Community",
    "test.title": "Parents & Students Love Us",
    "test.t1_name": "Ahmed Khan",
    "test.t1_role": "Parent",
    "test.t1_text": "My son's character has changed completely since he joined Al-Umaima. He is now focused and responsible.",
    "test.t2_name": "Fatima Bi",
    "test.t2_role": "Student",
    "test.t2_text": "The teachers here make learning Arabic so easy and enjoyable. I love the environment here.",
    "test.t3_name": "Sheikh Ibrahim",
    "test.t3_role": "Community Member",
    "test.t3_text": "A truly transparent organization that is making a real difference on the ground in our locality.",

    // Contact CTA
    "cta.title": "Have a Question?",
    "cta.subtitle": "\"Knowledge is a garden that must be tended together.\"",
    "cta.direct_line": "Direct Line",
    "cta.visit": "Visit Location",
    "cta.btn": "Contact Now",

    // Footer
    "footer.about": "Dedicated to nurturing the future generation with authentic Quranic knowledge, academic excellence, and exemplary Islamic character development.",
    "footer.links_title": "Quick Links",
    "footer.courses_title": "Our Courses",
    "footer.contact_title": "Contact Info",
    "footer.online_classes": "Online Classes",
    "footer.address": "Nashik, Maharashtra, India",
    "footer.phone_val": "+91 95276 35311",
    "footer.email_val": "info@madrasalumaima.edu",
    "footer.rights": "All rights reserved.",
    "footer.designed": "Designed with ❤️ for the Ummah.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",

    // About Page
    "about_p.hero_legacy": "Our Legacy & History",
    "about_p.hero_title": "About Al-Umaima",
    "about_p.hero_subtitle": "\"Nurturing the generation that will lead with light.\"",
    "about_p.journey_title": "Founding Vision",
    "about_p.journey_subtitle": "Establish in 1998 with only 5 students, now a globally recognized center of knowledge.",
    "about_p.journey_feat1_label": "Visionary Start",
    "about_p.journey_feat1_val": "Madrasa Al-Umaima began in a small community hall with the intention of providing authentic Tajweed education.",
    "about_p.journey_feat2_label": "Our Growth",
    "about_p.journey_feat2_val": "Over the years, we expanded into 3 distinct campuses covering Hifz, Alim, and Modern studies.",
    "about_p.journey_feat3_label": "Community Impact",
    "about_p.journey_feat3_val": "1200+ graduates are currently serving as Imam and educators across 14 countries.",
    "about_p.journey_campus_one": "Campus One",
    "about_p.journey_established": "Established: Since 1998",
    "about_p.journey_years": "Years of Service",
    "about_p.journey_alumni": "Alumni Success",
    "about_p.vision_title": "Our Vision",
    "about_p.vision_desc": "To be a leading center of Islamic and modern education that produces confident and competent leaders for the global Muslim community.",
    "about_p.mission_title": "Our Mission",
    "about_p.mission_desc": "To provide a nurturing environment where students excel in Quranic memorization while integrating secular knowledge and strong ethical character.",
    "about_p.values_title": "Core Values",
    "about_p.values_desc": "Ikhlas (Sincerity), Excellence, Integrity, and Service to Humanity are the pillars that support everything we do.",
    "about_p.goals_strategy": "Future Ready Strategy",
    "about_p.goals_title": "Institutional Goals",
    "about_p.goal1_title": "Spiritual Development",
    "about_p.goal1_desc": "Instilling deep love for Allah and the Sunnah of the Prophet (Peace be upon him) in every heart.",
    "about_p.goal2_title": "Academic Rigor",
    "about_p.goal2_desc": "Setting high standards for both Quranic memorization and English-medium academics.",
    "about_p.goal3_title": "Community Integration",
    "about_p.goal3_desc": "Creating strong ties between students, parents, and the local neighborhood for mutual growth.",
    "about_p.goal4_title": "Technological Proficiency",
    "about_p.goal4_desc": "Ensuring our graduates are well-versed in modern tools while staying grounded in tradition.",
    "about_p.enroll_btn": "Enroll Nominated Child",

    // Courses Page
    "courses_p.hero_label": "Educational Excellence",
    "courses_p.hero_title": "Our Core Programs",
    "courses_p.hero_subtitle": "\"Knowledge without practice is like a tree without fruit.\"",
    "courses_p.admission_fee": "Admission Fee",
    "courses_p.duration_label": "Duration",
    "courses_p.category_label": "Category",
    "courses_p.enroll_btn": "Enroll in Course",
    "courses_p.verified": "Verified Curriculum 2026",
    "courses_p.c3_title": "Urdu Language",
    "courses_p.c3_desc": "Master the Urdu language through classical literature and poetry.",
    "courses_p.c3_age": "8+ Years",
    "courses_p.c3_fee": "$15 / Mo",
    "courses_p.c4_title": "Arabic Language",
    "courses_p.c4_desc": "In-depth study of Modern Standard Arabic and Classical Quranic Arabic.",
    "courses_p.c4_age": "12+ Years",
    "courses_p.c4_fee": "$30 / Mo",
    "courses_p.c5_title": "Islamic Studies",
    "courses_p.c5_desc": "Comprehensive course on Fiqh, Seerah, Hadith, and Islamic History.",
    "courses_p.c5_age": "All Ages",
    "courses_p.c5_fee": "$25 / Mo",
    "courses_p.c6_title": "Basic Deeniyat",
    "courses_p.c6_desc": "Essential daily knowledge for children covering Duas and Sunnahs.",
    "courses_p.c6_age": "4-7 Years",
    "courses_p.c6_fee": "Free / Mo",
    "courses_p.c7_title": "Online Quran Classes",
    "courses_p.c7_desc": "Flexible remote learning for students across the globe with live sessions.",
    "courses_p.c7_age": "All Ages",
    "courses_p.c7_fee": "$50 / Mo",
    "courses_p.sch_title": "Scholarships Available",
    "courses_p.sch_desc": "\"The best of you are those who learn the Quran and teach it.\"",
    "courses_p.sch_btn": "Check Eligibility",
    "courses_p.faq_title": "Still Confused?",
    "courses_p.faq_desc": "Book a 1:1 Spiritual Counseling session with our scholars today.",
    "courses_p.faq_btn": "Schedule Meeting",

    // Admission Page
    "adm_p.success_title": "Alhamdulillah!",
    "adm_p.success_msg": "Your admission request has been successfully submitted. Our administrative team will reach out to you within 48-72 hours.",
    "adm_p.ref_id": "Reference ID",
    "adm_p.back_home": "Back To Home",
    "adm_p.new_admission": "New Admission",
    "adm_p.hero_label": "Academic Enrollment",
    "adm_p.hero_title": "Apply For",
    "adm_p.hero_accent": "Admission",
    "adm_p.hero_subtitle": "Join the legacy of Quranic and Scientific excellence.",
    "adm_p.process_title": "Selection Process",
    "adm_p.step1_title": "Apply Online",
    "adm_p.step1_desc": "Fill out the comprehensive admission form with correct details.",
    "adm_p.step2_title": "Entrance Test",
    "adm_p.step2_desc": "Candidates will be called for a 1:1 evaluation session.",
    "adm_p.step3_title": "Final Interview",
    "adm_p.step3_desc": "Interaction session with the Principal and the parents.",
    "adm_p.step4_title": "Fee Submission",
    "adm_p.step4_desc": "Submit the admission and monthly cycle fees for enrolment.",
    "adm_p.docs_title": "Required Documents",
    "adm_p.doc1": "Photocopy of CNIC / Form B",
    "adm_p.doc2": "2 Passport size photographs",
    "adm_p.doc3": "Previous Academic Report (if any)",
    "adm_p.doc4": "Address Proof / Residence Certificate",
    "adm_p.form_title": "Online Admission Form",
    "adm_p.form_subtitle": "Please provide authentic data only",
    "adm_p.full_name": "Full Name of Student",
    "adm_p.full_name_ph": "e.g. Mustafa Ahmed",
    "adm_p.parent_name": "Father/Guardian Name",
    "adm_p.parent_name_ph": "e.g. Ahmed Khan",
    "adm_p.dob": "Date of Birth",
    "adm_p.mobile": "Mobile Number",
    "adm_p.address": "Residential Address",
    "adm_p.address_ph": "Full address details here...",
    "adm_p.course_interest": "Course Interested In",
    "adm_p.course_select": "Select a Course",
    "adm_p.prev_edu": "Previous Education",
    "adm_p.prev_edu_ph": "e.g. Grade 5 / School Name",
    "adm_p.upload_photo": "Upload Student Photo",
    "adm_p.upload_ph": "Select File (JPG, PNG)",
    "adm_p.submit_btn": "Submit Admission Inquiry",
    "adm_p.policy_msg": "By submitting, you agree to our",
    "adm_p.policy_link": "Institutional Policy",

    // Donation Page
    "don_p.hero_label": "Charity & Service",
    "don_p.hero_title": "Support",
    "don_p.hero_accent": "Students",
    "don_p.hero_subtitle": "\"The believer's shade on the Day of Resurrection will be their charity.\"",
    "don_p.ways_label": "Make An Impact",
    "don_p.ways_title": "Ways To Give",
    "don_p.cat1_title": "Zakat",
    "don_p.cat1_desc": "Pure your wealth by supporting the deserving students and faculty.",
    "don_p.cat2_title": "Sadaqah",
    "don_p.cat2_desc": "A voluntary charity that brings barakah and spiritual fulfillment.",
    "don_p.cat3_title": "Lillah",
    "don_p.cat3_desc": "General donations for architecture and operational costs of the Madrasa.",
    "don_p.cat4_title": "Student Sponsor",
    "don_p.cat4_desc": "Fully support a child's education for an entire year (Hifz/Alim).",
    "don_p.cat5_title": "Building Fund",
    "don_p.cat5_desc": "Contribute to the expansion of our library and modern classrooms.",
    "don_p.cat6_title": "Ramadan Iftar",
    "don_p.cat6_desc": "Earn rewards by providing food for fasting students this holy month.",
    "don_p.cat_btn": "Choose",
    "don_p.details_label": "Direct Support",
    "don_p.details_title": "Financial Transparency",
    "don_p.details_subtitle": "We ensure 100% of your donation reaches the intended cause with complete audit reports.",
    "don_p.bank_label": "Bank Account",
    "don_p.account_name": "Account Name",
    "don_p.account_val": "AL-UMAIMA EDUCATION TRUST",
    "don_p.ifsc_label": "IFSC / SWIFT",
    "don_p.trust_verified": "Trustee Verified",
    "don_p.int_transfers": "International Transfers OK",
    "don_p.receipt_title": "Payment Receipt",
    "don_p.receipt_sub": "Instant Digital Acknowledgement",
    "don_p.qr_text": "Scan QR code for UPI & Wallet transfers.",
    "don_p.download_btn": "Download Guidelines",
    "don_p.reward_title": "A Journey of Reward",
    "don_p.reward_desc": "\"Your shadow in the Hereafter will be your charity on Earth. Let us build this legacy together, for our children and our afterlife.\"",
    "don_p.partner_btn": "Partner With Us Today",

    // Contact Page
    "con_p.hero_label": "Connect With Us",
    "con_p.hero_title": "Get In",
    "con_p.hero_accent": "Touch",
    "con_p.hero_subtitle": "\"Knowledge is a treasure; its key is the question.\"",
    "con_p.info_title": "Information Center",
    "con_p.info_subtitle": "Visit our administrative office for admission and donation queries.",
    "con_p.loc_label": "Our Location",
    "con_p.call_label": "Direct Call",
    "con_p.email_label": "Official Email",
    "con_p.careers": "Careers Info",
    "con_p.hours": "Visit Hours",
    "con_p.map_directions": "View Google Map Directions",
    "con_p.success_title": "JazakAllah Khair!",
    "con_p.success_msg": "Your message has been safely delivered to our inbox. We will get back to you shortly.",
    "con_p.send_another": "Send Another Message",
    "con_p.form_title": "Send A Message",
    "con_p.form_sub": "Connect with our support staff directly",
    "con_p.full_name": "Full Name",
    "con_p.phone": "Phone Number",
    "con_p.email": "Email Address",
    "con_p.subject": "Subject",
    "con_p.message": "Your Detailed Message",
    "con_p.submit_btn": "Deliver Consultation Message",
    "con_p.support_text": "Direct Contact Support:",
    "con_p.name_ph": "Your Name",
    "con_p.sub_ph": "Purpose of Enquiry",
    "con_p.msg_ph": "Type your message here...",
  },
  ur: {
    // Navbar / Common
    "nav.home": "ہوم",
    "nav.about": "ہمارے بارے میں",
    "nav.courses": "کورسز",
    "nav.admission": "داخلہ",
    "nav.teachers": "اساتذہ",
    "nav.notices": "اعلامیہ",
    "nav.contact": "رابطہ",
    "nav.gallery": "گیلری",
    "nav.donation": "عطیہ",
    "nav.login": "لاگ ان",
    "nav.madrasa_name": "مدرسہ العمیمہ",
    "nav.tagline": "قرآن و علم",

    // Dashboard Sidebar
    "side.dashboard": "ڈیش بورڈ",
    "side.profile": "میری پروفائل",
    "side.attendance": "حاضری",
    "side.fees": "فیس کی صورتحال",
    "side.results": "نتائج",
    "side.notice": "نوٹس بورڈ",
    "side.timetable": "ٹائم ٹیبل",
    "side.homework": "ہوم ورک",
    "side.id_card": "شناختی کارڈ",
    "side.report_card": "رزلٹ کارڈ",
    "side.settings": "سیٹنگز",
    "side.logout": "لاگ آؤٹ",
    "side.portal": "طالب علم پورٹل",

    // Common UI
    "btn.apply": "ابھی داخلہ لیں",
    "btn.donate": "عطیہ کریں",
    "btn.learn_more": "مزید جانیں",
    "btn.view_all": "سب دیکھیں",
    "btn.contact_now": "رابطہ کریں",
    "btn.submit": "پیغام بھیجیں",
    "btn.save": "تبدیلیاں محفوظ کریں",

    // Home Page
    "hero.title_p1": "ایک مقام برائے",
    "hero.title_quran": "قرآن",
    "hero.title_p2": "علم اور کردار",
    "hero.subtitle": "اگلی نسل کے مسلم لیڈروں کو کلاسیکی اسلامی تعلیم کے ساتھ بااختیار بنانا۔",
    "hero.admissions": "داخلے کھلے ہیں 2026-27",

    // Contact / Forms
    "form.full_name": "پورا نام",
    "form.phone": "فون نمبر",
    "form.email": "ای میل ایڈریس",
    "form.subject": "مضمون",
    "form.message": "آپ کا تفصیلی پیغام",
    "form.send": "مشاورتی پیغام ارسال کریں",
    "form.location_label": "ہمارا پتہ",
    "form.call_label": "براہ راست کال",
    "form.email_label": "سرکاری ای میل",

    // Profile / ID Card
    "profile.student_id": "اسٹوڈنٹ آئی ڈی",
    "profile.class": "کلاس",
    "profile.reg_date": "تاریخ رجسٹریشن",
    "profile.roll": "رول نمبر",
    "id.identity": "شناختی کارڈ",

    // Attendance / Fees / Stats
    "stat.present": "حاضر",
    "stat.absent": "غیر حاضر",
    "stat.late": "تاخیر",
    "stat.paid": "ادا شدہ",
    "stat.pending": "باقی",
    "stat.overdue": "واجب الادا",

    // Dashboard / Portal Extra
    "portal.welcome": "السلام علیکم",
    "portal.roll": "رول نمبر",
    "portal.dashboard": "اسٹوڈنٹ ڈیش بورڈ",
    "portal.quick_actions": "فوری کام",
    "portal.id_card_btn": "شناختی کارڈ",
    "portal.report_card_btn": "رزلٹ کارڈ",
    "portal.stats.attendance": "حاضری %",
    "portal.stats.fees": "باقی فیس",
    "portal.stats.course": "موجودہ کورس",
    "portal.alert.title": "تعلیمی اطلاعات",
    "portal.alert.recent": "اہم نوٹس",
    "portal.alert.view": "کارکردگی کی تفصیلات دیکھیں",
    "portal.recognition": "اعزاز",
    "portal.student_month": "ماہانہ بہترین طالب علم کا امیدوار",

    // Admission Page Extra
    "admission.hero.title": "داخلہ کے لیے",
    "admission.hero.accent": "درخواست دیں",
    "admission.hero.sub": "قرآنی اور سائنسی فضیلت کے ورثے میں شامل ہوں۔",
    "admission.process": "انتخاب کا طریقہ کار",
    "admission.docs": "مطلوبہ دستاویزات",
    "admission.form.title": "آن لائن داخلہ فارم",
    "admission.form.sub": "براہ کرم صرف مستند معلومات فراہم کریں",
    "admission.form.student_name": "طالب علم کا مکمل نام",
    "admission.form.parent_name": "والد یا سرپرست کا نام",
    "admission.form.dob": "تاریخ پیدائش",
    "admission.form.btn": "داخلہ کی درخواست جمع کروائیں",

    // Home Page - About Section
    "about.legacy": "ہمارا ورثہ",
    "about.title": "1998 سے روحوں کی آبیاری",
    "about.desc1": "مدرسہ العمیمہ کی بنیاد ایک واحد وژن کے ساتھ رکھی گئی تھی: ایک ایسی پناہ گاہ بنانا جہاں دل علم سے ملے۔ ہم سمجھتے ہیں کہ حقیقی تعلیم کتابوں سے بالاتر ہے — یہ کردار کی تبدیلی کے بارے میں ہے۔",
    "about.desc2": "ہمارا نصاب کلاسیکی \"درسِ نظامی\" کے طریقے پر مبنی ہے جبکہ اس میں جدید مواصلاتی مہارتیں اور سائنسی خواندگی کو بھی شامل کیا گیا ہے۔",
    "about.vision_label": "وژن",
    "about.vision_text": "مستند علم کے ذریعے امت کو بااختیار بنانا",
    "about.values_label": "اقدار",
    "about.values_text": "اخلاص، فضیلت، دیانت، خدمت",
    "about.learn_more": "ہمارے سفر کے بارے میں مزید جانیں",
    "about.masjid_learning": "مسجد پر مبنی تعلیم",
    "about.hifz_program": "کلاسیکی حفظ پروگرام",
    "about.student_centered": "طالب علم پر مرکوز",
    "about.global_standards": "عالمی معیار",

    // Why Choose Us Section
    "why.title": "العمیمہ کا انتخاب کیوں کریں؟",
    "why.subtitle": "\"علم حاصل کرنا ہر مسلمان پر فرض ہے۔\" - حدیث",
    "why.feat1_title": "اہل اساتذہ",
    "why.feat1_desc": "برسوں کے تجربے اور گہری روحانی بصیرت کے حامل مستند علماء اور حفاظ سے سیکھیں۔",
    "why.feat2_title": "محفوظ تعلیمی ماحول",
    "why.feat2_desc": "خاص طور پر ڈیزائن کی گئی جگہیں جو ہر عمر کے لیے توجہ، نظم و ضبط اور روحانی ترقی کو فروغ دیتی ہیں۔",
    "why.feat3_title": "کردار سازی",
    "why.feat3_desc": "ہم تعلیمی قابلیت کے ساتھ ساتھ اخلاق پر بھی توجہ دیتے ہیں، طلباء کو صرف امتحانات کے لیے نہیں بلکہ زندگی کے لیے تیار کرتے ہیں۔",
    "why.feat4_title": "قرآن اور اسلامی تعلیم",
    "why.feat4_desc": "تجوید، فقہ، سیرت اور اسلامی تاریخ پر مشتمل جامع ماڈیولز۔",
    "why.feat5_title": "سستی تعلیم",
    "why.feat5_desc": "متعدد اسکالرشپ پروگرام اور فیس کا لچکدار ڈھانچہ تاکہ علم تک رسائی یقینی بنائی جا سکے۔",
    "why.feat6_title": "کمیونٹی سپورٹ",
    "why.feat6_desc": "باقاعدہ ملاقاتوں اور ورکشاپس کے ذریعے والدین اور مقامی کمیونٹی کے ساتھ مضبوط تعلقات۔",

    // Course Preview
    "course.label": "ہمارے بنیادی پروگرام",
    "course.title": "تعلیمی فضیلت",
    "course.view_all": "تمام کورسز دیکھیں",
    "course.enroll_now": "داخلہ لیں",
    "course.c1_title": "ناظرہ قرآن",
    "course.c1_desc": "ابتدائی طلباء کے لیے تجوید کے قواعد کے ساتھ بنیادی پڑھائی۔",
    "course.c2_title": "حفظ القرآن",
    "course.c2_desc": "خوبصورت تجوید کے ساتھ قرآن پاک کا حفظ۔",
    "course.c3_title": "اردو اور عربی",
    "course.c3_desc": "قرآن کی زبان اور علاقائی ادب پر مہارت حاصل کریں۔",
    "course.c4_title": "اسلامی علوم",
    "course.c4_desc": "فقہ، سیرت اور حدیث پر مشتمل جامع کورس۔",
    "course.time_1y": "1 سال",
    "course.time_34y": "3-4 سال",
    "course.time_2y": "2 سال",
    "course.fee_monthly": "ماہانہ",
    "course.fee_semester": "سمسٹر",
    "course.fee_free": "مفت",

    // Founder Section
    "founder.badge": "قیادت کا پیغام",
    "founder.title": "الفاظ سے بالاتر حکمت",
    "founder.msg": "\"مدرسہ العمیمہ میں ہم طلباء کو صرف پڑھنا نہیں سکھا رہے، بلکہ ہم انہیں جینے کا طریقہ سکھا رہے ہیں۔ ہمارا مشن دلوں میں علم کے بیج بونا ہے تاکہ وہ حکمت کے درخت بن سکیں جو پوری امت کو سایہ فراہم کریں۔\"",
    "founder.name": "مولانا عبد العمیمہ",
    "founder.role": "ماہر اسلامی فقہ (عالم)",
    "founder.designation": "بانی اور پرنسپل",
    "founder.link": "ہمارے معلمین کا مکمل پروفائل",

    // Stats Section
    "stats.students": "طلباء",
    "stats.alumni": "سابق طلباء",
    "stats.teachers": "اساتذہ",
    "stats.courses": "کورسز",

    // Notice Board Section
    "notice.title": "نوٹس بورڈ",
    "notice.link": "تمام اعلانات",
    "notice.read_more": "تفصیلات دیکھیں",
    "notice.type_adm": "داخلہ",
    "notice.type_res": "نتائج",
    "notice.type_hol": "تعطیلات",
    "notice.n1_title": "داخلہ اوپن 2026",
    "notice.n1_date": "15 اپریل 2026",
    "notice.n1_desc": "نئے تعلیمی سیشن کے لیے تمام پروگراموں میں داخلے اب کھلے ہیں۔",
    "notice.n2_title": "سالانہ امتحان کے نتائج",
    "notice.n2_date": "20 مئی 2026",
    "notice.n2_desc": "سیشن 2025-26 کے نتائج اب اسٹوڈنٹ ڈیش بورڈ پر دستیاب ہیں۔",
    "notice.n3_title": "رمضان المبارک کی چھٹیاں",
    "notice.n3_date": "10 جنوری 2026",
    "notice.n3_desc": "مدرسہ 20 رمضان سے 5 شوال تک بند رہے گا۔",

    // Donation Section
    "donation.title": "اسلامی تعلیم کی حمایت کریں",
    "donation.desc": "مستحق طلباء کو معیاری تعلیم فراہم کرنے میں ہماری مدد کے لیے اپنی زکوٰۃ، صدقات اور للہ عطیہ کریں۔ ہر عطیہ ایک دل کو علم سے روشن کرتا ہے۔",
    "donation.btn": "ابھی عطیہ کریں",
    "donation.quick_pay": "فوری ادائیگی",
    "donation.scan_qr": "حمایت کے لیے QR اسکین کریں",
    "donation.bank": "بینک اکاؤنٹ",
    "donation.upi": "UPI ID",
    "donation.phonepay": "فون پے",

    // Testimonials Section
    "test.label": "ہماری کمیونٹی کی آوازیں",
    "test.title": "والدین اور طلباء ہم سے محبت کرتے ہیں",
    "test.t1_name": "احمد خان",
    "test.t1_role": "والد",
    "test.t1_text": "مدرسہ العمیمہ میں شامل ہونے کے بعد میرے بیٹے کا کردار مکمل طور پر بدل گیا ہے۔ وہ اب باوقار اور ذمہ دار ہے۔",
    "test.t2_name": "فاطمہ بی",
    "test.t2_role": "طالبہ",
    "test.t2_text": "یہاں کے اساتذہ عربی سیکھنا بہت آسان اور پرلطف بنا دیتے ہیں۔ مجھے یہاں کا ماحول بہت پسند ہے۔",
    "test.t3_name": "شیخ ابراہیم",
    "test.t3_role": "کمیونٹی ممبر",
    "test.t3_text": "ایک حقیقی شفاف تنظیم جو ہمارے علاقے میں زمینی سطح پر حقیقی تبدیلی لا رہی ہے۔",

    // Contact CTA
    "cta.title": "کوئی سوال ہے؟",
    "cta.subtitle": "\"علم ایک ایسا باغ ہے جس کی دیکھ بھال مل کر کرنی چاہیے۔\"",
    "cta.direct_line": "براہ راست لائن",
    "cta.visit": "پتہ",
    "cta.btn": "ابھی رابطہ کریں",

    // Footer
    "footer.about": "آنے والی نسل کو مستند قرآنی علم، تعلیمی فضیلت، اور مثالی اسلامی کردار کی نشوونما کے ساتھ پروان چڑھانے کے لیے وقف۔",
    "footer.links_title": "فوری لنکس",
    "footer.courses_title": "ہمارے کورسز",
    "footer.contact_title": "رابطہ کی معلومات",
    "footer.online_classes": "آن لائن کلاسز",
    "footer.address": "ناشک، مہاراشٹر، بھارت",
    "footer.phone_val": "+91 95276 35311",
    "footer.email_val": "info@madrasalumaima.edu",
    "footer.rights": "جملہ حقوق محفوظ ہیں۔",
    "footer.designed": "امت کے لیے محبت کے ساتھ ڈیزائن کیا گیا۔",
    "footer.privacy": "پرائیویسی پالیسی",
    "footer.terms": "سروس کی شرائط",

    // About Page
    "about_p.hero_legacy": "ہمارا ورثہ اور تاریخ",
    "about_p.hero_title": "العمیمہ کے بارے میں",
    "about_p.hero_subtitle": "\"اس نسل کی پرورش جو روشنی کے ساتھ قیادت کرے گی۔\"",
    "about_p.journey_title": "بانی کا وژن",
    "about_p.journey_subtitle": "صرف 5 طلباء کے ساتھ 1998 میں قائم ہوا، اب علم کا ایک عالمی سطح پر تسلیم شدہ مرکز ہے۔",
    "about_p.journey_feat1_label": "بصیرت افروز آغاز",
    "about_p.journey_feat1_val": "مدرسہ العمیمہ کا آغاز ایک مقامی کمیونٹی ہال میں مستند تجوید کی تعلیم فراہم کرنے کی نیت سے ہوا تھا۔",
    "about_p.journey_feat2_label": "ہماری ترقی",
    "about_p.journey_feat2_val": "برسوں کے دوران، ہم 3 الگ الگ کیمپسوں میں پھیل گئے جن میں حفظ، عالم اور جدید علوم شامل ہیں۔",
    "about_p.journey_feat3_label": "کمیونٹی پر اثر",
    "about_p.journey_feat3_val": "1200 سے زائد فارغ التحصیل طلباء اس وقت 14 ممالک میں امام اور اساتذہ کے طور پر خدمات انجام دے رہے ہیں۔",
    "about_p.journey_campus_one": "کیمپس ون",
    "about_p.journey_established": "قیام: 1998 سے",
    "about_p.journey_years": "خدمت کے سال",
    "about_p.journey_alumni": "کامیاب سابق طلباء",
    "about_p.vision_title": "ہمارا وژن",
    "about_p.vision_desc": "اسلامی اور جدید تعلیم کا ایک صفِ اول کا مرکز بننا جو عالمی مسلم کمیونٹی کے لیے پراعتماد اور قابل لیڈر پیدا کرے۔",
    "about_p.mission_title": "ہمارا مشن",
    "about_p.mission_desc": "ایک ایسا سازگار ماحول فراہم کرنا جہاں طلباء قرآن حفظ کرنے میں کمال حاصل کریں جبکہ دنیاوی علم اور مضبوط اخلاقی کردار کو بھی یکجا کریں۔",
    "about_p.values_title": "بنیادی اقدار",
    "about_p.values_desc": "اخلاص، فضیلت، دیانت، اور انسانیت کی خدمت وہ ستون ہیں جو ہمارے ہر کام کی بنیاد ہیں۔",
    "about_p.goals_strategy": "مستقبل کے لیے تیار حکمت عملی",
    "about_p.goals_title": "ادارہ جاتی مقاصد",
    "about_p.goal1_title": "روحانی ترقی",
    "about_p.goal1_desc": "ہر دل میں اللہ تعالیٰ اور نبی کریم صلی اللہ علیہ وسلم کی سنت کی گہری محبت پیدا کرنا۔",
    "about_p.goal2_title": "تعلیمی معیار",
    "about_p.goal2_desc": "حفظ قرآن اور انگریزی میڈیم تعلیمی معیار دونوں کے لیے اعلیٰ معیارات کا تعین کرنا۔",
    "about_p.goal3_title": "کمیونٹی انضمام",
    "about_p.goal3_desc": "باہمی ترقی کے لیے طلباء، والدین اور مقامی کمیونٹی کے درمیان مضبوط تعلقات قائم کرنا۔",
    "about_p.goal4_title": "تکنیکی مہارت",
    "about_p.goal4_desc": "اس بات کو یقینی بنانا کہ ہمارے گریجویٹس روایات پر قائم رہتے ہوئے جدید ٹولز سے بخوبی واقف ہوں۔",
    "about_p.enroll_btn": "بچے کا داخلہ کروائیں",

    // Courses Page
    "courses_p.hero_label": "تعلیمی فضیلت",
    "courses_p.hero_title": "ہمارے بنیادی پروگرام",
    "courses_p.hero_subtitle": "\"عمل کے بغیر علم ایسا ہے جیسے پھل کے بغیر درخت۔\"",
    "courses_p.admission_fee": "داخلہ فیس",
    "courses_p.duration_label": "دورانیہ",
    "courses_p.category_label": "زمرہ",
    "courses_p.enroll_btn": "کورس میں داخلہ لیں",
    "courses_p.verified": "تصدیق شدہ نصاب 2026",
    "courses_p.c3_title": "اردو زبان",
    "courses_p.c3_desc": "کلاسک ادب اور شاعری کے ذریعے اردو زبان پر مہارت حاصل کریں۔",
    "courses_p.c3_age": "8 سال سے زائد",
    "courses_p.c3_fee": "15 ڈالر / ماہانہ",
    "courses_p.c4_title": "عربی زبان",
    "courses_p.c4_desc": "جدید معیاری عربی اور کلاسیکی قرآنی عربی کا گہرا مطالعہ۔",
    "courses_p.c4_age": "12 سال سے زائد",
    "courses_p.c4_fee": "30 ڈالر / ماہانہ",
    "courses_p.c5_title": "اسلامی علوم",
    "courses_p.c5_desc": "فقہ، سیرت، حدیث اور اسلامی تاریخ پر مبنی جامع کورس۔",
    "courses_p.c5_age": "تمام عمر کے لیے",
    "courses_p.c5_fee": "25 ڈالر / ماہانہ",
    "courses_p.c6_title": "بنیادی دینیات",
    "courses_p.c6_desc": "بچوں کے لیے روزانہ کا ضروری علم جس میں دعائیں اور سنتیں شامل ہیں۔",
    "courses_p.c6_age": "4-7 سال",
    "courses_p.c6_fee": "مفت / ماہانہ",
    "courses_p.c7_title": "آن لائن قرآن کلاسز",
    "courses_p.c7_desc": "براہ راست سیشنز کے ساتھ دنیا بھر کے طلباء کے لیے لچکدار ریموٹ لرننگ۔",
    "courses_p.c7_age": "تمام عمر کے لیے",
    "courses_p.c7_fee": "50 ڈالر / ماہانہ",
    "courses_p.sch_title": "اسکالرشپ دستیاب ہے",
    "courses_p.sch_desc": "\"تم میں سے بہتر وہ ہے جو قرآن سیکھے اور سکھائے۔\"",
    "courses_p.sch_btn": "اہلیت چیک کریں",
    "courses_p.faq_title": "کیا اب بھی الجھن ہے؟",
    "courses_p.faq_desc": "آج ہی ہمارے علماء کے ساتھ 1:1 روحانی مشاورت کا سیشن بک کریں۔",
    "courses_p.faq_btn": "ملاقات کا وقت طے کریں",

    // Admission Page
    "adm_p.success_title": "الحمد للہ!",
    "adm_p.success_msg": "آپ کی داخلہ کی درخواست کامیابی کے ساتھ جمع کر دی گئی ہے۔ ہمارا انتظامی عملہ ۴۸ سے ۷۲ گھنٹوں کے اندر آپ سے رابطہ کرے گا۔",
    "adm_p.ref_id": "حوالہ نمبر",
    "adm_p.back_home": "ہوم پیج پر واپس جائیں",
    "adm_p.new_admission": "نیا داخلہ",
    "adm_p.hero_label": "تعلیمی داخلہ",
    "adm_p.hero_title": "داخلہ کے لیے",
    "adm_p.hero_accent": "درخواست دیں",
    "adm_p.hero_subtitle": "قرآنی اور سائنسی فضیلت کے ورثے میں شامل ہوں۔",
    "adm_p.process_title": "انتخاب کا طریقہ کار",
    "adm_p.step1_title": "آن لائن اپلائی کریں",
    "adm_p.step1_desc": "درست تفصیلات کے ساتھ جامع ایڈمیشن فارم پُر کریں۔",
    "adm_p.step2_title": "داخلہ ٹیسٹ",
    "adm_p.step2_desc": "امیدواروں کو ون ٹو ون جانچ کے سیشن کے لیے بلایا جائے گا۔",
    "adm_p.step3_title": "آخری انٹرویو",
    "adm_p.step3_desc": "پرنسپل اور والدین کے ساتھ بات چیت کا سیشن۔",
    "adm_p.step4_title": "فیس جمع کروانا",
    "adm_p.step4_desc": "داخلے کے لیے ایڈمیشن اور ماہانہ فیس جمع کروائیں۔",
    "adm_p.docs_title": "مطلوبہ دستاویزات",
    "adm_p.doc1": "شناختی کارڈ یا فارم بی کی فوٹو کاپی",
    "adm_p.doc2": "۲ پاسپورٹ سائز تصاویر",
    "adm_p.doc3": "پچھلی تعلیمی رپورٹ (اگر ہو)",
    "adm_p.doc4": "پتے کا ثبوت یا رہائشی سرٹیفکیٹ",
    "adm_p.form_title": "آن لائن داخلہ فارم",
    "adm_p.form_subtitle": "براہ کرم صرف مستند معلومات فراہم کریں",
    "adm_p.full_name": "طالب علم کا مکمل نام",
    "adm_p.full_name_ph": "جیسے: مصطفی احمد",
    "adm_p.parent_name": "والد یا سرپرست کا نام",
    "adm_p.parent_name_ph": "جیسے: احمد خان",
    "adm_p.dob": "تاریخ پیدائش",
    "adm_p.mobile": "موبائل نمبر",
    "adm_p.address": "رہائشی پتہ",
    "adm_p.address_ph": "پتہ کی مکمل تفصیلات یہاں لکھیں...",
    "adm_p.course_interest": "کورس جس میں دلچسپی ہے",
    "adm_p.course_select": "کورس منتخب کریں",
    "adm_p.prev_edu": "سابقہ تعلیم",
    "adm_p.prev_edu_ph": "مثلاً: گریڈ ۵ / اسکول کا نام",
    "adm_p.upload_photo": "طالب علم کی تصویر اپ لوڈ کریں",
    "adm_p.upload_ph": "فائل منتخب کریں (JPG, PNG)",
    "adm_p.submit_btn": "داخلہ کی درخواست جمع کروائیں",
    "adm_p.policy_msg": "جمع کروا کر، آپ ہماری",
    "adm_p.policy_link": "ادارہ جاتی پالیسی",
    "adm_p.policy_agree": "سے اتفاق کرتے ہیں",

    // Donation Page
    "don_p.hero_label": "صدقہ اور خدمت",
    "don_p.hero_title": "طلباء کی",
    "don_p.hero_accent": "حمایت کریں",
    "don_p.hero_subtitle": "\"قیامت کے دن مومن کا سایہ اس کا صدقہ ہوگا۔\"",
    "don_p.ways_label": "اثر ڈالیں",
    "don_p.ways_title": "عطیہ دینے کے طریقے",
    "don_p.cat1_title": "زکوٰۃ",
    "don_p.cat1_desc": "مستحق طلباء اور اساتذہ کی مدد کر کے اپنے مال کو پاک کریں۔",
    "don_p.cat2_title": "صدقہ",
    "don_p.cat2_desc": "ایک نفلی صدقہ جو برکت اور روحانی سکون لاتا ہے۔",
    "don_p.cat3_title": "للہ",
    "don_p.cat3_desc": "مدرسہ کے انفراسٹرکچر اور آپریشنل اخراجات کے لیے عام عطیات۔",
    "don_p.cat4_title": "طالب علم کی کفالت",
    "don_p.cat4_desc": "پورے ایک سال کے لیے بچے کی تعلیم (حفظ/عالم) کی مکمل کفالت کریں۔",
    "don_p.cat5_title": "تعمیراتی فنڈ",
    "don_p.cat5_desc": "ہماری لائبریری اور جدید کلاس رومز کی توسیع میں حصہ ڈالیں۔",
    "don_p.cat6_title": "رمضان افطار",
    "don_p.cat6_desc": "اس مقدس مہینے میں روزہ دار طلباء کے لیے کھانے کا انتظام کر کے اجر کمائیں۔",
    "don_p.cat_btn": "منتخب کریں",
    "don_p.details_label": "براہ راست تعاون",
    "don_p.details_title": "مالی شفافیت",
    "don_p.details_subtitle": "ہم اس بات کو یقینی بناتے ہیں کہ آپ کے عطیہ کا ۱۰۰ فیصد حصہ مطلوبہ مقصد تک پہنچے جس کی آڈٹ رپورٹ مکمل طور پر دستیاب ہوگی۔",
    "don_p.bank_label": "بینک اکاؤنٹ",
    "don_p.account_name": "اکاؤنٹ کا نام",
    "don_p.account_val": "العمیمہ ایجوکیشن ٹرسٹ",
    "don_p.ifsc_label": "IFSC / SWIFT کوڈ",
    "don_p.trust_verified": "ٹرسٹی سے تصدیق شدہ",
    "don_p.int_transfers": "بین الاقوامی منتقلی ممکن ہے",
    "don_p.receipt_title": "ادائیگی کی رسید",
    "don_p.receipt_sub": "فوری ڈیجیٹل رسید",
    "don_p.qr_text": "UPI اور والٹ ٹرانسفر کے لیے QR کوڈ اسکین کریں۔",
    "don_p.download_btn": "رہنما اصول ڈاؤن لوڈ کریں",
    "don_p.reward_title": "اجر کا سفر",
    "don_p.reward_desc": "\"آخرت میں آپ کا سایہ زمین پر آپ کا صدقہ ہوگا۔ آئیے مل کر اپنے بچوں اور اپنی آخرت کے لیے یہ وراثت بنائیں۔\"",
    "don_p.partner_btn": "آج ہی ہمارے ساتھ شامل ہوں",

    // Contact Page
    "con_p.hero_label": "ہم سے رابطہ کریں",
    "con_p.hero_title": "رابطہ",
    "con_p.hero_accent": "میں رہیں",
    "con_p.hero_subtitle": "\"علم ایک خزانہ ہے؛ اس کی کلید سوال ہے۔\"",
    "con_p.info_title": "معلومات کا مرکز",
    "con_p.info_subtitle": "داخلہ اور عطیہ سے متعلق سوالات کے لیے ہمارے انتظامی دفتر کا دورہ کریں۔",
    "con_p.loc_label": "ہمارا مقام",
    "con_p.call_label": "براہ راست کال",
    "con_p.email_label": "سرکاری ای میل",
    "con_p.careers": "ملازمت کی معلومات",
    "con_p.hours": "ملاقات کے اوقات",
    "con_p.map_directions": "گوگل میپ کی سمتیں دیکھیں",
    "con_p.success_title": "جزاک اللہ خیر!",
    "con_p.success_msg": "آپ کا پیغام کامیابی کے ساتھ ہمارے ان باکس میں پہنچ گیا ہے۔ ہم جلد ہی آپ سے رابطہ کریں گے۔",
    "con_p.send_another": "دوسرا پیغام بھیجیں",
    "con_p.form_title": "پیغام بھیجیں",
    "con_p.form_sub": "ہمارے معاون عملے سے براہ راست رابطہ کریں",
    "con_p.full_name": "مکمل نام",
    "con_p.phone": "فون نمبر",
    "con_p.email": "ای میل ایڈریس",
    "con_p.subject": "مضمون",
    "con_p.message": "آپ کا تفصیلی پیغام",
    "con_p.submit_btn": "مشاورتی پیغام ارسال کریں",
    "con_p.support_text": "براہ راست رابطہ معاونت:",
    "con_p.name_ph": "آپ کا نام",
    "con_p.sub_ph": "انکوائری کا مقصد",
    "con_p.msg_ph": "اپنا پیغام یہاں لکھیں...",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en");

  // Load from local storage
  useEffect(() => {
    const saved = localStorage.getItem("app-lang") as Language;
    if (saved) setLanguage(saved);
  }, []);

  useEffect(() => {
    localStorage.setItem("app-lang", language);
    // Apply RTL to HTML tag
    document.documentElement.dir = language === "ur" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => (prev === "en" ? "ur" : "en"));
  };

  const t = (key: string) => {
    return translations[language]?.[key] || key;
  };

  const isUrdu = language === "ur";

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isUrdu }}>
      <div className={isUrdu ? "font-urdu" : "font-sans"}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
