# Generated by Django 6.1 on 2026-08-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Zakat', 'Zakat'), ('Sadqah', 'Sadqah'), ('General Fund', 'General Madrasa Fund'), ('Building Fund', 'Building & Infrastructure Fund'), ('Orphan Support', 'Orphan & Needy Student Support')], default='General Fund', max_length=50)),
                ('payment_method', models.CharField(default='Online', max_length=30)),
                ('status', models.CharField(default='Paid', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payee_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Tuition Fee', 'Tuition Fee'), ('Registration', 'Registration'), ('Donation', 'Donation'), ('Hostel Fee', 'Hostel Fee'), ('Exam Fee', 'Exam Fee'), ('Books & Supplies', 'Books & Supplies'), ('Other', 'Other')], default='Tuition Fee', max_length=50)),
                ('method', models.CharField(choices=[('Online', 'Online Payment / Card'), ('Cash', 'Cash Receipt'), ('Bank', 'Bank Transfer'), ('Cheque', 'Cheque / DD')], default='Online', max_length=30)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending Approval'), ('Due', 'Payment Due'), ('Cancelled', 'Cancelled')], db_index=True, default='Paid', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
